import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import React from "react";
import { Flowbite, Sidebar } from "flowbite-react";
import SidebarNew from "@/components/Sidebar";
import FlowbiteWrapper from "@/components/FlowbiteWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App1 ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen overflow-auto">
          <FlowbiteWrapper>
            <Layout />
            <div className="flex-1 flex h-full">
              <SidebarNew />
              {children}
            </div>
          </FlowbiteWrapper>
        </div>
      </body>
    </html>
  );
}
